import { z } from "zod";
import { readWorkspaceState, writeWorkspaceState } from "./storage";

export const materialRegistrySchema = z.object({
  studies: z.array(z.object({ id: z.string().min(1).max(120), objective: z.string().max(3000), unitOfAnalysis: z.string().max(500), sampleSource: z.string().max(1000), eligibility: z.string().max(3000), randomisation: z.string().max(3000), ethicsStatus: z.enum(["pending", "submitted", "approved"]), preregistrationUrl: z.string().url().or(z.literal("")), materialsAvailability: z.enum(["planned", "private", "open"]), dataAvailability: z.enum(["planned", "private", "open"]), codeAvailability: z.enum(["planned", "private", "open"]), notes: z.string().max(3000) })).max(100),
  stimuli: z.array(z.object({ id: z.string().min(1).max(120), studyId: z.string().max(120), name: z.string().max(300), version: z.string().max(80), productionProtocol: z.string().max(5000), modelVersion: z.string().max(200), promptVersion: z.string().max(120), factSheetId: z.string().max(120), sellerVerification: z.string().max(2000), equivalenceCheck: z.string().max(3000), pretestId: z.string().max(120), rightsStatus: z.enum(["unknown", "cleared", "restricted", "prohibited"]), externalModelUsePermission: z.enum(["unknown", "allowed", "prohibited"]), notes: z.string().max(3000) })).max(500),
  instruments: z.array(z.object({ id: z.string().min(1).max(120), constructId: z.string().max(120), name: z.string().max(300), conceptualDefinition: z.string().max(3000), itemSourceWorkId: z.string().max(120), itemSourceLocator: z.string().max(500), permissionStatus: z.enum(["unknown", "cleared", "restricted", "prohibited"]), adaptationRecord: z.string().max(3000), items: z.array(z.object({ id: z.string().max(120), wording: z.string().max(1000), responseScale: z.string().max(500), reverseCoded: z.boolean() })).max(100), validationStatus: z.enum(["unverified", "pretest", "reliable", "validity-reviewed"]), notes: z.string().max(3000) })).max(500),
  pretests: z.array(z.object({ id: z.string().min(1).max(120), target: z.enum(["stimulus", "manipulation", "measurement"]), sampleSource: z.string().max(1000), sampleN: z.number().int().nonnegative().nullable(), procedure: z.string().max(3000), outcome: z.string().max(3000), status: z.enum(["planned", "completed", "reviewed"]), notes: z.string().max(3000) })).max(300),
  updatedAt: z.string().max(80),
});
export type MaterialRegistry = z.infer<typeof materialRegistrySchema>;
export function readMaterialRegistry(projectId?: string): MaterialRegistry { const parsed = materialRegistrySchema.safeParse(readWorkspaceState<unknown>("material_registry", projectId)); if (parsed.success) return parsed.data; const initial: MaterialRegistry = { studies: [], stimuli: [], instruments: [], pretests: [], updatedAt: new Date().toISOString() }; writeWorkspaceState("material_registry", initial, projectId); return initial; }
export function saveMaterialRegistry(input: MaterialRegistry, projectId?: string) { const registry = materialRegistrySchema.parse({ ...input, updatedAt: new Date().toISOString() }); writeWorkspaceState("material_registry", registry, projectId); return registry; }
