import { NextResponse } from "next/server";
import { getProjectDocument } from "@/lib/project-documents";
import { runCitationAudit, latestAudit } from "@/lib/citation-audit";
import { runConsistencyReview, latestConsistencyReview } from "@/lib/consistency-review";
import { saveDocumentApproval, savePublicationStatusOverride } from "@/lib/evidence-store";
import { listQuarantinedDrafts } from "@/lib/evidence-store";
import { compileClaimCoverage, latestClaimCoverage } from "@/lib/claim-coverage";
import { checkFormalExportGate } from "@/lib/formal-export-gate";
export const runtime = "nodejs";
type Context = { params: Promise<{ projectId: string; documentId: string }> };
export async function GET(_request: Request, context: Context) { const { projectId, documentId } = await context.params; if (!getProjectDocument(projectId, documentId)) return NextResponse.json({ error: "文档不存在。" }, { status: 404 }); return NextResponse.json({ citationAudit: latestAudit(projectId, documentId), consistencyReview: latestConsistencyReview(projectId, documentId), claimCoverage: latestClaimCoverage(projectId, documentId), quarantinedDrafts: listQuarantinedDrafts(projectId, documentId) }); }
export async function POST(request: Request, context: Context) { const { projectId, documentId } = await context.params; if (!getProjectDocument(projectId, documentId)) return NextResponse.json({ error: "文档不存在。" }, { status: 404 }); const body = await request.json().catch(() => ({})); const versionId = typeof body.versionId === "string" ? body.versionId : undefined; if (body.type === "citation") return NextResponse.json(await runCitationAudit({ projectId, documentId, versionId, formal: body.formal === true })); if (body.type === "coverage") return NextResponse.json(await compileClaimCoverage({ projectId, documentId, versionId, classifierMode: body.classifierMode === "model" ? "model" : "deterministic" })); if (body.type === "formal-export-gate") return NextResponse.json(await checkFormalExportGate({ projectId, documentId, versionId })); if (body.type === "consistency") return NextResponse.json(await runConsistencyReview({ projectId, documentId, versionId })); if (body.type === "document-approval" && versionId && ["approved", "changes_requested"].includes(body.decision) && typeof body.reviewer === "string") return NextResponse.json(saveDocumentApproval({ projectId, documentId, documentVersionId: versionId, decision: body.decision, reviewer: body.reviewer, notes: typeof body.notes === "string" ? body.notes : undefined })); if (body.type === "publication-status-override" && versionId && typeof body.workId === "string" && typeof body.reviewer === "string" && typeof body.reason === "string") return NextResponse.json(savePublicationStatusOverride({ projectId, workId: body.workId, documentVersionId: versionId, reviewer: body.reviewer, reason: body.reason })); return NextResponse.json({ error: "审查类型无效，或缺少 versionId/reviewer。" }, { status: 400 }); }
